# Generated by Django 6.0.2 on 2026-03-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='diastolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='systolic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
    ]
